export const DELETE_HISTORY_REQUEST = "DELETE_HISTORY_REQUEST";
export const DELETE_HISTORY_SUCCESS = "DELETE_HISTORY_SUCCESS";
export const DELETE_HISTORY_FAIL = "DELETE_HISTORY_FAIL";

export const DELETE_ALL_HISTORY_REQUEST = "DELETE_ALL_HISTORY_REQUEST";
export const DELETE_ALL_HISTORY_SUCCESS = "DELETE_ALL_HISTORY_SUCCESS";
export const DELETE_ALL_HISTORY_FAIL = "DELETE_ALL_HISTORY_FAIL";
