export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAIL = "CREATE_TRANSACTION_FAIL";

export const TRANSACTION_SUMMARY_REQUEST = "TRANSACTION_SUMMARY_REQUEST";
export const TRANSACTION_SUMMARY_SUCCESS = "TRANSACTION_SUMMARY_SUCCESS";
export const TRANSACTION_SUMMARY_FAIL = "TRANSACTION_SUMMARY_FAIL";

export const RESET_ORDER = "RESET_ORDER";
