export const ADD_USER_INFO = "ADD_USER_INFO";
export const REMOVE_USER_INFO = "REMOVE_USER_INFO";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_CONFIRMATION_REQUEST = "USER_CONFIRMATION_REQUEST";
export const USER_CONFIRMATION_SUCCESS = "USER_CONFIRMATION_SUCCESS";
export const USER_CONFIRMATION_FAIL = "USER_CONFIRMATION_FAIL";

export const USER_PAYMENT_REQUEST = "USER_PAYMENT_REQUEST";
export const USER_PAYMENT_SUCCESS = "USER_PAYMENT_SUCCESS";
export const USER_PAYMENT_FAIL = "USER_PAYMENT_FAIL";

export const USER_HISTORY_REQUEST = "USER_HISTORY_REQUEST";
export const USER_HISTORY_SUCCESS = "USER_HISTORY_SUCCESS";
export const USER_HISTORY_FAIL = "USER_HISTORY_FAIL";

export const RESET_STATE = "RESET_STATE";
